name: Daily LME Automation

on:
  schedule:
    # Runs every day at 12:00 UTC (08:00 America/New_York during EDT).
    - cron: "0 12 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: lme-automation
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # Set these in: Repo → Settings → Secrets and variables → Actions
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 selenium supabase python-dotenv

      - name: Run scraper
        run: python Scraper.py
