name: Scraping Commodities.

on:
  schedule:
    - cron: '0 6 * * 2-6'  # Runs at 6am UTC on Tue-Sat
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
          # Set these in: Repo → Settings → Secrets and variables → Actions
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 selenium supabase python-dotenv

      - name: Run script
        run: |
          python Scraper.py
